print('<html>')
print('<head>')
print('<title>Hello Word - First CGI Program</title>')
print('</head>')
print('<body>')
print('<h2>Hello Word! This is my first CGI program on python</h2>')
print('<a href="/test_cgi_py/game.py" style="font-family:Monotype Corsiva;color:black;font-size:25px">Game</a><br/>')
print('<a href="/" style="font-family:Monotype Corsiva;color:black;font-size:25px">HOME</a>')
print('</body>')
print('</html>')
